"""Generates docs/data/recipes.json — original AllVeg recipe library (36 recipes)."""
import json, pathlib

def R(id, title, emoji, cat, cuisine, tags, time, serv, kcal, pro, carb, fat, rating, votes, summary, ing, steps, tip):
    return dict(id=id, title=title, emoji=emoji, cat=cat, cuisine=cuisine, tags=tags, time=time, servings=serv,
                nutrition=dict(kcal=kcal, protein=pro, carbs=carb, fat=fat), rating=rating, votes=votes,
                summary=summary, ingredients=[dict(q=q, u=u, n=n) for q, u, n in ing], steps=steps, tip=tip)

recipes = [
R("chickpea-shakshuka","Chickpea Shakshuka","🍅","breakfast","Middle Eastern",["vegan","high-protein","gluten-free","budget"],25,4,310,14,38,11,4.9,412,
 "Smoky tomato-pepper sauce with chickpeas standing in for eggs. One pan, 25 minutes, endlessly dippable.",
 [(2,"tbsp","olive oil"),(1,"","onion, diced"),(1,"","red bell pepper, sliced"),(3,"cloves","garlic, minced"),(1,"tsp","smoked paprika"),(1,"tsp","ground cumin"),(800,"g","canned crushed tomatoes"),(400,"g","canned chickpeas, drained"),(0.5,"tsp","salt"),(1,"handful","fresh parsley or cilantro")],
 ["Warm oil in a wide skillet over medium heat; soften onion and pepper 6–7 min.","Stir in garlic, paprika and cumin for 1 min until fragrant.","Add tomatoes and salt, simmer 8 min until thickened.","Fold in chickpeas, simmer 5 min. Make wells and spoon a little sauce over each.","Scatter herbs, serve with warm flatbread or crusty bread."],
 "Add 100 g crumbled tofu into the wells for an egg-like finish."),
R("overnight-oats-pb","Peanut Butter Banana Overnight Oats","🥣","breakfast","American",["vegan","high-protein","quick","budget"],5,1,420,17,58,14,4.8,689,
 "Five-minute prep, zero cooking, 17 g protein. The breakfast that survives any morning.",
 [(50,"g","rolled oats"),(1,"tbsp","chia seeds"),(1,"tbsp","peanut butter"),(180,"ml","soy milk"),(1,"","ripe banana, mashed"),(1,"tsp","maple syrup"),(1,"pinch","cinnamon")],
 ["Mash banana in a jar; stir in peanut butter and maple syrup.","Add oats, chia, cinnamon and milk; stir well.","Seal and refrigerate at least 4 hours or overnight.","Top with sliced banana or berries before eating."],
 "Use soy milk over oat milk: it roughly doubles the protein."),
R("tofu-scramble","Turmeric Tofu Scramble","🍳","breakfast","American",["vegan","high-protein","gluten-free","quick"],15,2,260,21,9,16,4.7,533,
 "Fluffy, savoury and ready in 15 minutes. Kala namak is the secret to the egg flavour.",
 [(400,"g","firm tofu, pressed"),(1,"tbsp","olive oil"),(0.5,"tsp","turmeric"),(0.5,"tsp","kala namak (black salt)"),(2,"tbsp","nutritional yeast"),(1,"","scallion, sliced"),(60,"g","baby spinach"),(0.25,"tsp","black pepper")],
 ["Crumble tofu with your hands into rough chunks.","Heat oil in a non-stick pan; add tofu and cook 4 min without stirring to brown.","Sprinkle turmeric, nutritional yeast and pepper; toss 3 min.","Add spinach and scallion, wilt 1 min. Finish with kala namak off the heat."],
 "Adding kala namak at the very end keeps its sulphur aroma intact."),
R("green-smoothie-bowl","Mango Spinach Smoothie Bowl","🥭","breakfast","Global",["vegan","gluten-free","quick"],8,1,330,9,62,7,4.6,201,
 "Bright, thick and spoonable. Freeze the mango the night before for a soft-serve texture.",
 [(150,"g","frozen mango"),(1,"","frozen banana"),(40,"g","baby spinach"),(120,"ml","oat milk"),(1,"tbsp","hemp seeds"),(2,"tbsp","granola"),(1,"tbsp","coconut flakes")],
 ["Blend mango, banana, spinach and milk until thick; add milk a splash at a time.","Spoon into a bowl.","Top with hemp seeds, granola and coconut."],
 "Less liquid = thicker bowl. Stop the blender and scrape down rather than adding milk."),
R("masala-oats-upma","Masala Oats Upma","🌶️","breakfast","Indian",["vegan","quick","budget"],15,2,280,9,44,8,4.7,318,
 "A savoury South-Indian style oats upma — mustard seeds, curry leaves and vegetables in 15 minutes.",
 [(1,"cup","rolled oats"),(1,"tbsp","oil"),(1,"tsp","mustard seeds"),(8,"","curry leaves"),(1,"","onion, chopped"),(1,"","green chilli, slit"),(1,"","carrot, finely diced"),(0.5,"cup","green peas"),(0.5,"tsp","turmeric"),(2,"cups","water"),(0.75,"tsp","salt"),(1,"tbsp","lemon juice")],
 ["Dry-roast oats 3 min; set aside.","Heat oil; pop mustard seeds, add curry leaves, chilli and onion. Sauté 3 min.","Add carrot, peas, turmeric and salt; cook 3 min.","Pour in water, bring to boil, stir in oats. Cook 3–4 min until absorbed.","Finish with lemon juice."],
 "Add a handful of roasted peanuts for crunch and protein."),
R("banana-pancakes","Fluffy Vegan Banana Pancakes","🥞","breakfast","American",["vegan","budget"],20,3,340,8,64,6,4.8,745,
 "No eggs, no dairy, still fluffy: the trick is baking powder plus a rested batter.",
 [(1.5,"cups","all-purpose flour"),(1,"tbsp","baking powder"),(1,"tbsp","sugar"),(0.25,"tsp","salt"),(1,"","very ripe banana"),(1.25,"cups","plant milk"),(1,"tbsp","oil"),(1,"tsp","vanilla")],
 ["Whisk flour, baking powder, sugar and salt.","Mash banana; whisk with milk, oil and vanilla.","Fold wet into dry until just combined; rest 5 min.","Cook ¼-cup scoops on a lightly oiled pan 2–3 min per side."],
 "Do not overmix; lumps mean fluff."),
R("buddha-bowl","Roasted Sweet Potato Buddha Bowl","🥗","lunch","Global",["vegan","gluten-free","high-protein"],35,2,540,20,72,20,4.9,912,
 "Roasted sweet potato, crispy chickpeas, greens and tahini-lemon drizzle. Meal prep gold.",
 [(1,"large","sweet potato, cubed"),(400,"g","canned chickpeas, drained"),(2,"tbsp","olive oil"),(1,"tsp","smoked paprika"),(150,"g","cooked quinoa"),(80,"g","kale, massaged"),(1,"","avocado, sliced"),(2,"tbsp","tahini"),(1,"tbsp","lemon juice"),(2,"tbsp","water"),(1,"pinch","salt")],
 ["Heat oven to 220°C / 425°F. Toss sweet potato and chickpeas with oil, paprika and salt.","Roast 25 min, shaking once.","Whisk tahini, lemon, water and salt into a pourable dressing.","Build bowls: quinoa, kale, roasted veg, avocado; drizzle dressing."],
 "Roast the chickpeas on a separate tray for maximum crunch."),
R("lentil-soup","Red Lentil & Coconut Soup","🍲","lunch","Indian",["vegan","gluten-free","high-protein","budget"],30,4,360,18,46,12,4.8,1024,
 "Creamy, gently spiced and under $1.50 a bowl. Freezes perfectly.",
 [(1,"tbsp","coconut oil"),(1,"","onion, diced"),(2,"cloves","garlic"),(1,"tbsp","grated ginger"),(1,"tbsp","curry powder"),(250,"g","red lentils, rinsed"),(400,"ml","coconut milk"),(1,"L","vegetable stock"),(2,"","tomatoes, chopped"),(1,"","lime, juiced"),(1,"tsp","salt")],
 ["Sauté onion in oil 5 min; add garlic, ginger and curry powder 1 min.","Add lentils, tomatoes, stock and coconut milk. Simmer 20 min, stirring occasionally.","Blend half for a creamier texture if you like.","Season with salt and lime; serve with rice or naan."],
 "Rinse lentils until the water runs clear to avoid a muddy flavour."),
R("chickpea-salad-sandwich","Smashed Chickpea Salad Sandwich","🥪","lunch","American",["vegan","high-protein","quick","budget"],10,2,430,16,58,15,4.7,388,
 "Tuna-salad energy with zero tuna. Ten minutes, one fork.",
 [(400,"g","canned chickpeas, drained"),(2,"tbsp","vegan mayo"),(1,"tsp","Dijon mustard"),(1,"","celery stalk, diced"),(2,"tbsp","red onion, minced"),(1,"tbsp","capers or dill pickle"),(1,"tsp","lemon juice"),(4,"slices","whole-grain bread"),(1,"handful","lettuce")],
 ["Mash chickpeas roughly with a fork, leaving texture.","Stir in mayo, mustard, celery, onion, capers and lemon; season.","Pile onto bread with lettuce."],
 "A sheet of nori, crumbled in, gives a subtle sea flavour."),
R("peanut-noodle-salad","Cold Peanut Noodle Salad","🥜","lunch","Thai",["vegan","quick","high-protein"],20,3,520,19,68,20,4.8,566,
 "Chilled rice noodles in a punchy peanut-lime dressing, loaded with crunchy veg and edamame.",
 [(200,"g","rice noodles"),(150,"g","shelled edamame"),(1,"","carrot, julienned"),(1,"","red pepper, sliced"),(1,"","cucumber, sliced"),(3,"tbsp","peanut butter"),(2,"tbsp","soy sauce"),(1,"tbsp","lime juice"),(1,"tbsp","maple syrup"),(1,"tsp","sriracha"),(3,"tbsp","warm water"),(2,"tbsp","crushed peanuts")],
 ["Cook noodles per pack; rinse under cold water.","Whisk peanut butter, soy, lime, maple, sriracha and water until smooth.","Toss noodles, edamame and vegetables with dressing.","Top with crushed peanuts."],
 "Dressing too thick? Add warm water a teaspoon at a time."),
R("caprese-quinoa","Caprese Quinoa Salad","🍅","lunch","Italian",["vegetarian","gluten-free","quick"],20,4,380,15,42,17,4.6,240,
 "Fresh mozzarella, cherry tomatoes and basil folded through lemony quinoa.",
 [(1,"cup","quinoa, rinsed"),(2,"cups","water"),(250,"g","cherry tomatoes, halved"),(150,"g","mini mozzarella balls"),(1,"handful","basil leaves"),(2,"tbsp","olive oil"),(1,"tbsp","balsamic vinegar"),(0.5,"tsp","salt")],
 ["Simmer quinoa in water 15 min; fluff and cool.","Toss with tomatoes, mozzarella and torn basil.","Dress with oil, vinegar and salt."],
 "Swap mozzarella for marinated tofu cubes to make it vegan."),
R("falafel-wrap","Baked Falafel Wrap","🌯","lunch","Middle Eastern",["vegan","high-protein","budget"],40,4,480,18,66,16,4.8,701,
 "Crisp baked falafel, no deep fryer, wrapped with pickles, tomato and tahini.",
 [(250,"g","dried chickpeas, soaked overnight"),(1,"","small onion"),(3,"cloves","garlic"),(1,"bunch","parsley"),(1,"tsp","cumin"),(1,"tsp","coriander"),(0.5,"tsp","baking soda"),(2,"tbsp","flour"),(1,"tsp","salt"),(2,"tbsp","olive oil"),(4,"","flatbreads"),(4,"tbsp","tahini sauce"),(1,"cup","tomato & pickle slices")],
 ["Pulse drained chickpeas, onion, garlic, parsley, spices, baking soda, flour and salt into a coarse paste.","Shape 16 balls; brush with oil.","Bake at 200°C / 400°F for 25 min, turning halfway.","Wrap in flatbread with tahini, tomato and pickles."],
 "Use soaked, not canned, chickpeas — canned makes mushy falafel."),
R("paneer-butter-masala","Paneer Butter Masala","🧀","dinner","Indian",["vegetarian","gluten-free","high-protein"],40,4,520,22,24,38,4.9,1340,
 "Restaurant-style silky tomato-cashew gravy with soft paneer — the most-requested Indian veg dish.",
 [(400,"g","paneer, cubed"),(3,"tbsp","butter"),(1,"","onion, chopped"),(4,"","tomatoes, chopped"),(15,"","cashews"),(1,"tbsp","ginger-garlic paste"),(1,"tsp","Kashmiri chilli powder"),(1,"tsp","garam masala"),(1,"tsp","sugar"),(100,"ml","cream"),(1,"tsp","kasuri methi"),(1,"tsp","salt")],
 ["Melt 1 tbsp butter; sauté onion, ginger-garlic, tomatoes and cashews 10 min. Cool, blend smooth.","Melt remaining butter; add chilli powder and the purée. Simmer 10 min.","Add sugar, salt, garam masala and cream. Simmer 5 min.","Add paneer and crushed kasuri methi; simmer 3 min."],
 "Soak paneer in warm salted water 10 min before adding for extra softness."),
R("mushroom-stroganoff","Creamy Mushroom Stroganoff","🍄","dinner","European",["vegan","quick"],25,4,470,14,62,18,4.8,655,
 "Cashew cream, caramelised mushrooms and paprika over pasta or rice in 25 minutes.",
 [(500,"g","mixed mushrooms, sliced"),(2,"tbsp","olive oil"),(1,"","onion, sliced"),(3,"cloves","garlic"),(1,"tbsp","smoked paprika"),(1,"tbsp","soy sauce"),(1,"tbsp","Dijon mustard"),(80,"g","cashews, soaked"),(250,"ml","vegetable stock"),(300,"g","pasta or rice"),(1,"handful","parsley")],
 ["Cook pasta. Blend cashews with stock until smooth.","Sear mushrooms in oil in batches until browned; set aside.","Soften onion and garlic; add paprika, soy and mustard.","Return mushrooms, pour in cashew cream, simmer 5 min. Toss with pasta and parsley."],
 "Crowding the pan steams mushrooms — sear in two batches."),
R("black-bean-tacos","Crispy Black Bean Tacos","🌮","dinner","Mexican",["vegan","gluten-free","quick","budget","high-protein"],20,4,450,17,64,14,4.8,899,
 "Pan-crisped corn tortillas stuffed with spiced black beans and a quick lime slaw.",
 [(800,"g","canned black beans, drained"),(1,"tsp","cumin"),(1,"tsp","chilli powder"),(0.5,"tsp","garlic powder"),(8,"","corn tortillas"),(2,"tbsp","oil"),(2,"cups","shredded cabbage"),(1,"","lime, juiced"),(1,"","avocado"),(0.5,"tsp","salt")],
 ["Mash beans with spices and salt.","Spread beans on half of each tortilla, fold.","Pan-fry in oil 2–3 min per side until crisp.","Toss cabbage with lime and salt; fill tacos with slaw and avocado."],
 "Warm tortillas first so they fold without cracking."),
R("thai-green-curry","Thai Green Curry with Tofu","🍛","dinner","Thai",["vegan","gluten-free"],30,4,490,17,40,30,4.7,612,
 "Fragrant coconut curry with crisp tofu, green beans and Thai basil.",
 [(400,"g","firm tofu, cubed"),(2,"tbsp","oil"),(3,"tbsp","vegan green curry paste"),(400,"ml","coconut milk"),(200,"ml","vegetable stock"),(150,"g","green beans"),(1,"","red pepper"),(1,"tbsp","soy sauce"),(1,"tsp","sugar"),(1,"handful","Thai basil"),(2,"cups","cooked jasmine rice")],
 ["Pan-fry tofu in 1 tbsp oil until golden; set aside.","Fry curry paste in remaining oil 1 min; add coconut milk and stock.","Add beans and pepper; simmer 8 min.","Return tofu, add soy and sugar; finish with basil. Serve over rice."],
 "Check the paste label — many contain shrimp."),
R("lentil-bolognese","Lentil Bolognese","🍝","dinner","Italian",["vegan","high-protein","budget"],45,6,510,22,78,10,4.9,1567,
 "Slow-simmered brown lentils, mushrooms and red wine make a rich ragù that fools omnivores.",
 [(2,"tbsp","olive oil"),(1,"","onion, diced"),(2,"","carrots, diced"),(2,"stalks","celery, diced"),(4,"cloves","garlic"),(250,"g","mushrooms, minced"),(250,"g","brown lentils"),(120,"ml","red wine"),(800,"g","canned crushed tomatoes"),(500,"ml","vegetable stock"),(2,"tsp","dried oregano"),(500,"g","spaghetti"),(1,"tsp","salt")],
 ["Sweat onion, carrot and celery 8 min; add garlic and mushrooms 5 min.","Add wine, reduce 2 min.","Add lentils, tomatoes, stock and oregano. Simmer 30 min until lentils are tender.","Season; serve over spaghetti."],
 "A teaspoon of miso or soy sauce deepens the umami."),
R("chana-masala","Chana Masala","🫘","dinner","Indian",["vegan","gluten-free","high-protein","budget"],35,4,390,16,60,9,4.9,1893,
 "The classic North-Indian chickpea curry: tangy, spiced and ready in 35 minutes with canned chickpeas.",
 [(2,"tbsp","oil"),(1,"tsp","cumin seeds"),(1,"","onion, finely chopped"),(1,"tbsp","ginger-garlic paste"),(2,"","tomatoes, puréed"),(1,"tsp","coriander powder"),(0.5,"tsp","turmeric"),(1,"tsp","chilli powder"),(1,"tsp","garam masala"),(1,"tsp","amchur (dry mango powder)"),(800,"g","canned chickpeas"),(250,"ml","water"),(1,"tsp","salt"),(1,"handful","cilantro")],
 ["Crackle cumin in oil; brown onion 8 min.","Add ginger-garlic, then tomato purée and powdered spices; cook until oil separates.","Add chickpeas, water and salt; simmer 15 min, mashing a few.","Finish with garam masala, amchur and cilantro."],
 "Simmer with a tea bag for the dark dhaba-style colour."),
R("stuffed-peppers","Quinoa Stuffed Peppers","🫑","dinner","Mediterranean",["vegan","gluten-free","high-protein"],50,4,410,15,60,13,4.6,377,
 "Bell peppers filled with herby quinoa, black beans and corn, baked until tender.",
 [(4,"","bell peppers, halved"),(1,"cup","quinoa"),(2,"cups","vegetable stock"),(400,"g","canned black beans"),(1,"cup","corn"),(1,"cup","salsa"),(1,"tsp","cumin"),(1,"tsp","smoked paprika"),(1,"handful","cilantro"),(0.5,"cup","vegan cheese (optional)")],
 ["Cook quinoa in stock 15 min.","Mix quinoa, beans, corn, salsa, spices and cilantro.","Fill pepper halves; top with cheese if using.","Bake covered at 190°C / 375°F for 30 min; uncover 5 min."],
 "Pre-roast the empty peppers 10 min for a softer bite."),
R("teriyaki-tempeh","Sticky Teriyaki Tempeh Bowls","🍱","dinner","Japanese",["vegan","high-protein","quick"],25,2,560,29,64,19,4.7,441,
 "Tempeh delivers 29 g protein per bowl under a glossy homemade teriyaki glaze.",
 [(250,"g","tempeh, sliced"),(1,"tbsp","oil"),(3,"tbsp","soy sauce"),(2,"tbsp","maple syrup"),(1,"tbsp","rice vinegar"),(1,"tsp","grated ginger"),(1,"clove","garlic"),(1,"tsp","cornstarch"),(2,"tbsp","water"),(2,"cups","cooked rice"),(1,"cup","steamed broccoli"),(1,"tsp","sesame seeds")],
 ["Steam tempeh 8 min to remove bitterness; pat dry.","Pan-fry in oil until golden on both sides.","Whisk soy, maple, vinegar, ginger, garlic, cornstarch and water; pour over tempeh, simmer until glossy.","Serve over rice with broccoli and sesame."],
 "Steaming first is the difference between bitter and delicious tempeh."),
R("veg-lasagna","Spinach & Cashew Ricotta Lasagna","🍽️","dinner","Italian",["vegan","high-protein"],75,8,480,18,56,20,4.8,528,
 "Layers of tofu-cashew ricotta, spinach and marinara — the Sunday centrepiece.",
 [(400,"g","firm tofu"),(100,"g","cashews, soaked"),(3,"tbsp","nutritional yeast"),(2,"tbsp","lemon juice"),(2,"cloves","garlic"),(300,"g","spinach, wilted and squeezed"),(700,"ml","marinara sauce"),(12,"","lasagna sheets"),(1,"tsp","salt"),(1,"tsp","dried basil")],
 ["Blend tofu, cashews, yeast, lemon, garlic, salt and basil into ricotta; stir in spinach.","Layer sauce, sheets, ricotta; repeat three times, ending with sauce.","Cover with foil; bake at 190°C / 375°F for 45 min. Uncover for 10 min.","Rest 15 min before slicing."],
 "Rest time matters — cutting early gives you soup."),
R("dal-tadka","Dal Tadka","🍛","dinner","Indian",["vegan","gluten-free","high-protein","budget"],35,4,300,15,44,8,4.9,2210,
 "Yellow lentils tempered with garlic, cumin and dried chilli. Comfort food at under $1 a serving.",
 [(1,"cup","toor or masoor dal"),(3,"cups","water"),(0.5,"tsp","turmeric"),(1,"tsp","salt"),(2,"tbsp","ghee or oil"),(1,"tsp","cumin seeds"),(4,"cloves","garlic, sliced"),(2,"","dried red chillies"),(1,"","onion, chopped"),(1,"","tomato, chopped"),(0.5,"tsp","chilli powder"),(1,"handful","cilantro")],
 ["Pressure-cook or simmer dal with turmeric, salt and water until soft (20–25 min); whisk smooth.","Heat ghee; crackle cumin, add garlic and dried chillies until golden.","Add onion, cook 5 min; add tomato and chilli powder 3 min.","Pour tempering over dal, simmer 5 min, top with cilantro."],
 "Add a squeeze of lemon right before serving."),
R("shepherds-pie","Lentil Shepherd's Pie","🥧","dinner","British",["vegan","high-protein","budget"],60,6,450,17,70,11,4.7,634,
 "Savoury lentil-vegetable base under a blanket of fluffy mash.",
 [(1,"kg","potatoes"),(60,"ml","plant milk"),(2,"tbsp","vegan butter"),(1,"tbsp","olive oil"),(1,"","onion"),(2,"","carrots"),(2,"cloves","garlic"),(250,"g","green lentils"),(2,"tbsp","tomato paste"),(500,"ml","vegetable stock"),(1,"cup","frozen peas"),(1,"tsp","thyme"),(1,"tbsp","soy sauce")],
 ["Boil potatoes; mash with milk and butter.","Sauté onion, carrot and garlic; add lentils, tomato paste, stock, thyme and soy. Simmer 25 min.","Stir in peas; spread in a dish, top with mash.","Bake at 200°C / 400°F for 25 min until golden."],
 "Rake the mash with a fork for maximum crispy ridges."),
R("veggie-burger","Ultimate Black Bean Burger","🍔","dinner","American",["vegan","high-protein"],35,4,430,17,58,14,4.8,1105,
 "Holds together, chars on the grill and doesn't taste like mush. Walnuts and oats are the secret.",
 [(800,"g","canned black beans, dried in the oven 10 min"),(60,"g","walnuts"),(60,"g","rolled oats"),(1,"","small onion"),(2,"cloves","garlic"),(2,"tbsp","soy sauce"),(1,"tbsp","tomato paste"),(1,"tsp","cumin"),(1,"tsp","smoked paprika"),(2,"tbsp","ground flax + 5 tbsp water"),(4,"","burger buns")],
 ["Pulse walnuts and oats to crumbs; add remaining ingredients and pulse to a chunky paste.","Chill 20 min; shape 4 patties.","Pan-fry or grill 5 min per side.","Serve on toasted buns with your favourite toppings."],
 "Drying the beans in the oven prevents soggy patties."),
R("coconut-chickpea-curry","10-Minute Coconut Chickpea Curry","🥥","dinner","Indian",["vegan","gluten-free","quick","budget","high-protein"],10,3,420,14,44,22,4.7,977,
 "Pantry-only curry for nights when cooking feels impossible.",
 [(1,"tbsp","oil"),(2,"tbsp","curry paste or 1 tbsp curry powder"),(400,"g","canned chickpeas"),(400,"ml","coconut milk"),(200,"g","frozen spinach"),(1,"tbsp","lime juice"),(0.5,"tsp","salt")],
 ["Fry curry paste in oil 1 min.","Add chickpeas, coconut milk and spinach; simmer 7 min.","Season with lime and salt. Serve over rice or with naan."],
 "Keep canned chickpeas and coconut milk stocked and dinner is always 10 minutes away."),
R("energy-balls","No-Bake Peanut Butter Energy Balls","⚡","snack","Global",["vegan","gluten-free","quick","high-protein"],10,12,120,4,13,6,4.8,832,
 "Twelve bites, ten minutes, no oven. The gym-bag snack.",
 [(1,"cup","rolled oats"),(0.5,"cup","peanut butter"),(3,"tbsp","maple syrup"),(2,"tbsp","ground flax"),(2,"tbsp","mini dark chocolate chips"),(1,"pinch","salt")],
 ["Stir everything together until it holds.","Roll into 12 balls; chill 30 min."],
 "Too dry? A teaspoon of plant milk fixes it."),
R("roasted-chickpeas","Crunchy Spiced Roasted Chickpeas","🫘","snack","Global",["vegan","gluten-free","budget","high-protein"],35,4,180,8,24,6,4.6,455,
 "Crispier than chips, with 8 g protein a handful.",
 [(800,"g","canned chickpeas, drained and dried"),(1.5,"tbsp","olive oil"),(1,"tsp","smoked paprika"),(0.5,"tsp","garlic powder"),(0.5,"tsp","salt")],
 ["Dry chickpeas thoroughly on a towel.","Roast plain at 200°C / 400°F for 20 min.","Toss with oil and spices; roast 10 more min."],
 "Season after the first roast — oil and spice too early make them soft."),
R("hummus","Silky Classic Hummus","🥙","snack","Middle Eastern",["vegan","gluten-free","quick","budget"],10,6,190,6,18,11,4.9,1266,
 "The smoothest hummus comes from over-cooked chickpeas and ice-cold water.",
 [(400,"g","canned chickpeas"),(0.25,"tsp","baking soda"),(4,"tbsp","tahini"),(2,"tbsp","lemon juice"),(1,"clove","garlic"),(3,"tbsp","ice water"),(2,"tbsp","olive oil"),(0.5,"tsp","cumin"),(0.5,"tsp","salt")],
 ["Simmer chickpeas with baking soda 10 min until very soft; drain.","Blend tahini, lemon, garlic and salt first; then add chickpeas.","Stream in ice water while blending until silky. Finish with oil and cumin."],
 "Blend a full 3 minutes — patience makes it whipped."),
R("kale-chips","Cheesy Kale Chips","🥬","snack","American",["vegan","gluten-free","quick"],20,2,110,5,10,7,4.5,289,
 "Nutritional yeast makes these addictively cheesy.",
 [(1,"bunch","kale, torn"),(1,"tbsp","olive oil"),(2,"tbsp","nutritional yeast"),(0.5,"tsp","salt")],
 ["Massage kale with oil, yeast and salt.","Bake in a single layer at 150°C / 300°F for 15–18 min until crisp."],
 "Low temperature is essential — high heat burns before it crisps."),
R("chocolate-avocado-mousse","Chocolate Avocado Mousse","🍫","dessert","Global",["vegan","gluten-free","quick"],10,4,260,4,26,17,4.7,674,
 "Five ingredients, five minutes, nobody can taste the avocado.",
 [(2,"","ripe avocados"),(4,"tbsp","cocoa powder"),(4,"tbsp","maple syrup"),(60,"ml","plant milk"),(1,"tsp","vanilla"),(1,"pinch","salt")],
 ["Blend everything until completely smooth, scraping down twice.","Chill 1 hour; top with berries."],
 "Use avocados that give slightly to pressure — underripe ones taste grassy."),
R("banana-bread","One-Bowl Vegan Banana Bread","🍌","dessert","American",["vegan","budget"],65,10,240,4,40,8,4.9,1580,
 "Moist, caramel-edged and made in one bowl with a fork.",
 [(3,"","very ripe bananas"),(80,"ml","oil"),(120,"g","brown sugar"),(1,"tsp","vanilla"),(220,"g","all-purpose flour"),(1,"tsp","baking soda"),(0.5,"tsp","cinnamon"),(0.5,"tsp","salt"),(60,"g","walnuts (optional)")],
 ["Mash bananas; stir in oil, sugar and vanilla.","Add flour, soda, cinnamon and salt; fold until just combined. Add walnuts.","Bake in a lined loaf tin at 175°C / 350°F for 50–55 min."],
 "Bananas should be nearly black for the deepest flavour."),
R("chia-pudding","Vanilla Chia Pudding","🍮","dessert","Global",["vegan","gluten-free","quick"],5,2,230,7,22,13,4.6,502,
 "Two-minute prep, overnight set. Works as breakfast or dessert.",
 [(4,"tbsp","chia seeds"),(250,"ml","coconut or soy milk"),(1,"tbsp","maple syrup"),(0.5,"tsp","vanilla"),(1,"cup","berries")],
 ["Whisk chia, milk, maple and vanilla. Whisk again after 10 min to prevent clumps.","Refrigerate at least 4 hours; top with berries."],
 "The second whisk is the difference between pudding and clumps."),
R("mango-lassi","Vegan Mango Lassi","🥤","drink","Indian",["vegan","gluten-free","quick"],5,2,210,5,40,4,4.8,398,
 "The classic Indian yogurt drink, made with coconut yogurt.",
 [(2,"cups","ripe mango chunks"),(1,"cup","coconut or soy yogurt"),(0.5,"cup","plant milk"),(1,"tbsp","maple syrup"),(0.25,"tsp","cardamom"),(4,"","ice cubes")],
 ["Blend all ingredients until smooth.","Serve immediately over ice."],
 "Alphonso or Kesar mango makes it exceptional; frozen mango works too."),
R("golden-milk","Golden Turmeric Latte","☕","drink","Indian",["vegan","gluten-free","quick"],5,1,120,3,14,6,4.6,277,
 "Warm, anti-inflammatory and calming. The evening ritual.",
 [(250,"ml","oat milk"),(0.5,"tsp","turmeric"),(0.25,"tsp","cinnamon"),(1,"pinch","black pepper"),(1,"pinch","ginger"),(1,"tsp","maple syrup")],
 ["Warm milk with spices, whisking, until steaming.","Sweeten and serve."],
 "Black pepper boosts curcumin absorption up to 20x."),
R("protein-smoothie","Chocolate Peanut Protein Smoothie","🥤","drink","American",["vegan","gluten-free","quick","high-protein"],5,1,390,30,42,12,4.8,721,
 "Thirty grams of protein, no chalky aftertaste.",
 [(1,"scoop","plant protein powder (chocolate)"),(1,"","frozen banana"),(1,"tbsp","peanut butter"),(300,"ml","soy milk"),(1,"tbsp","cocoa powder"),(1,"handful","ice")],
 ["Blend until smooth; add ice for thickness."],
 "Soy milk adds 9 g protein per glass — the best plant milk for gains."),
R("crispy-tofu","Crispy Baked Tofu (Master Recipe)","🧊","dinner","Asian",["vegan","gluten-free","high-protein","budget"],35,3,220,20,10,12,4.9,1712,
 "The foundational technique: press, cornstarch, high heat. Crisp every time.",
 [(400,"g","extra-firm tofu"),(1,"tbsp","soy sauce or tamari"),(1,"tbsp","oil"),(1.5,"tbsp","cornstarch"),(0.5,"tsp","garlic powder")],
 ["Press tofu 15 min; tear into rough chunks.","Toss with soy and oil, then cornstarch and garlic powder.","Bake at 220°C / 425°F for 25–30 min, flipping halfway."],
 "Tearing instead of cubing creates craggy edges that crisp better."),
]
out = pathlib.Path(__file__).resolve().parent.parent / "docs/data/recipes.json"
out.write_text(json.dumps(recipes, ensure_ascii=False, indent=1))
print(len(recipes), "recipes ->", out)
